create table CMDB
(Name varchar(36),
Manufacturer varchar (24),
Model varchar (28),
Serial_Number varchar (14),
Campus varchar (8),
Building varchar (38),
Room_Number varchar (12),
Cooling_Device varchar (26),
Power_Device varchar (32),
Department varchar (28),
Last_Edit_Date_Time varchar (14),
Purchase_Order varchar (10),
Service_Contract_End_Date varchar (8),
Service_Contract_Number varchar (16),
Service_Contract_Purchase_Order varchar (10),
Service_Contract_Start_Date varchar (7),
Service_Contract_Term varchar (23),
DEVICE_TYPE varchar (32));

